version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - app
      - mysqldb
    volumes:
      - ./src:/var/www
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d

  mysqldb:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./etc/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_mysql
      MYSQL_ROOT_PASSWORD: mysql_pwd

  pgdb:
    image: postgres
    container_name: postgres
    volumes:
      - ./etc/pgsql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel_pgsql
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pgsql_pwd

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - pgdb
    environment:
      PGADMIN_DEFAULT_EMAIL: jfhogan2@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password

  app:
    container_name: laravel_pgsql_mysql
    build:
      context: etc/fpm
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
